CREATE TABLE CATEGORY 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) NOT NULL 
, TAX NUMBER DEFAULT 0 NOT NULL 
, CONSTRAINT CATEGORY_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CATEGORY_PK ON CATEGORY (ID ASC) 
      LOGGING 
      TABLESPACE GENERAL 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE GENERAL 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;


CREATE TABLE BILL_HISTORY 
(
  ID NUMBER NOT NULL 
, CUST_NAME VARCHAR2(100 BYTE) NOT NULL 
, TXN_TIME TIMESTAMP(6) 
, CONSTRAINT BILL_HISTORY_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BILL_HISTORY_PK ON BILL_HISTORY (ID ASC) 
      LOGGING 
      TABLESPACE GENERAL 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE GENERAL 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;


CREATE TABLE PRODUCT_LIST 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) NOT NULL 
, CATEGORY_FK NUMBER 
, PRICE NUMBER 
, BILL_FK NUMBER 
, CONSTRAINT PRODUCT_LIST_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PRODUCT_LIST_PK ON PRODUCT_LIST (ID ASC) 
      LOGGING 
      TABLESPACE GENERAL 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE GENERAL 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE PRODUCT_LIST
ADD CONSTRAINT BILLHIST_FK FOREIGN KEY
(
  BILL_FK 
)
REFERENCES BILL_HISTORY
(
  ID 
)
ENABLE;

ALTER TABLE PRODUCT_LIST
ADD CONSTRAINT CATEG_FK FOREIGN KEY
(
  CATEGORY_FK 
)
REFERENCES CATEGORY
(
  ID 
)
ENABLE;


CREATE SEQUENCE SEQ INCREMENT BY 1 START WITH 1000 MAXVALUE 9999 MINVALUE 1000 CACHE 20;
